config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts, only: [:create, :edit, :update, :index]
    delete "posts/:id" => "posts#destroy", as: "post_destroy"

 root "posts#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [ :create, :update, :edit, :destroy]
	def index
		@post=Post.new
	end

	def create
		@post= Post.create(
                 title: params[:post][:title],
                 content: params[:post][:content],
                  user_id: current_user.id
			)
	end
    def edit
		@post=Post.find(params[:id])

		if @post.user_id != current_user.id
        redirect_to action: "index"
    
    end
	def update
		@post=Post.find(params[:id])
		@post.update(
			title: params[:post][:title],
          content: params[:post][:content]
           )
		redirect_to action: 'index'
	end

	
	def destroy
		@post= Post.find(params[:id])
		if @post.user_id != current_user.id
        redirect_to action: "index"
   else
		@post.destroy
	end

	end

end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Plantrip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_post.html.erb
<li id="post<%= post.id %>"" class="post-list">
	<p class="post-content">Title : <%= post.title%></p>
	<p class="post-content">Content : <%= post.content%></p>
	<p class ="post-user">
		<small>

			By <%= post.user.email %>
			at <%= post.created_at.to_date %>
	

		</small>
	</p>
	<p>
   <% if current_user == post.user %>
	<%= link_to "Delete", post_destroy_path(post.id),  :method => 'delete',remote: true %> -
	<%= link_to "Edit", edit_post_path(post.id),  :method => 'get' %>
    <% end %>
	</p>
</li>

app/views/posts/create.js.erb
$('#p').prepend('<%= escape_javascript render "post", post: @post %>');

app/views/posts/destroy.js.erb
console.log("post destoyed")
$('#post<%=@post.id%>').remove();

app/views/posts/edit.html.erb
<h3> Update Post </h3>
<%= form_for @post do |p| %>
<%= p.label :content, "Content" %>
<%= p.text_field :content %>
<%= p.submit %>
<%end%>

app/views/posts/index.html.erb
<main class= "body-main">
	
    <div id="new-post">
   	<h3> Posts </h3>
   	<%= form_for @post, remote: true do |f|%>
   	<%= f.label :title, "New Trip"%>

   	<%= f.text_field :title %>
   	<br><br>
   	<br>
   	<%= f.label :content, "Details" %>
   	<%= f.text_field :content %>
   	<br><br>
   	<%= f.submit %>
   	<%end%>
   </div>

   <div class="posts-list-container center-container">
	    <ul id="p">

		<% Post.all.reverse.each do |p| %>

		 <%= render "post" , post: p %>
		
		 <% end %>
		</ul>

		
	</div>
</main>